// Code generated by MockIO. DO NOT EDIT.
// Source: logger.go

// Package mockio_logger is a generated GoMock package.
package mockio_logger

import (
	logger "github.com/ispec-inc/go-distributed-monolith/pkg/logger"
)

type LoggerError struct {
	Time    int
	ArgUser logger.User
	ArgErr  logger.Error
}
