# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "mysql2"
gem "standalone_migrations"

gem "activesupport"
gem "activerecord"
gem "seed-fu"
