version: '2.2'
services:
  protoc:
    container_name: protoc
    build:
      context: .
      dockerfile: proto/docker/Dockerfile
    volumes:
      - ./:/workspace
    networks:
      - monorepo

  gen:
    container_name: gen
    build:
      context: .
      dockerfile: gen/docker/Dockerfile
    env_file:
      - gen/.env
    volumes:
      - ./:/workspace
    working_dir: /workspace
    networks:
      - monorepo

networks:
  monorepo:
    external: true
