# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monorepopb/server/api/user/user.proto

require 'google/protobuf'

require 'monorepopb/server/view/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("monorepopb/server/api/user/user.proto", :syntax => :proto3) do
    add_message "monorepopb.server.api.user.GetRequest" do
    end
    add_message "monorepopb.server.api.user.GetResponse" do
      optional :user, :message, 1, "monorepopb.server.view.User"
    end
    add_message "monorepopb.server.api.user.CreateRequest" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :email, :string, 3
    end
    add_message "monorepopb.server.api.user.CreateResponse" do
      repeated :users, :message, 1, "monorepopb.server.view.User"
    end
  end
end

module UserPb
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("monorepopb.server.api.user.GetRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("monorepopb.server.api.user.GetResponse").msgclass
  CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("monorepopb.server.api.user.CreateRequest").msgclass
  CreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("monorepopb.server.api.user.CreateResponse").msgclass
end
