default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  timeout: 5000
  port: <%= ENV.fetch("DB_PORT") %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
