// Code generated by MockIO. DO NOT EDIT.
// Source: invitation.go

// Package mockio_repository is a generated GoMock package.
package mockio_repository

import (
	model "github.com/ispec-inc/go-distributed-monolith/pkg/domain/model"
)

type InvitationCreate struct {
	Time    int
	ArgMinv model.Invitation
	Ret0    error
}

type InvitationFind struct {
	Time  int
	ArgId int64
	Ret0  model.Invitation
	Ret1  error
}

type InvitationFindByUserID struct {
	Time   int
	ArgUid int64
	Ret0   model.Invitation
	Ret1   error
}
