// Code generated by MockIO. DO NOT EDIT.
// Source: user.go

// Package mockio_repository is a generated GoMock package.
package mockio_repository

import (
	model "github.com/ispec-inc/monorepo/server/pkg/domain/model"
)

type UserCreate struct {
	Time    int
	ArgUser *model.User
	Ret0    error
}

type UserGet struct {
	Time  int
	ArgId int64
	Ret0  *model.User
	Ret1  error
}

type UserList struct {
	Time   int
	ArgIds []int64
	Ret0   []*model.User
	Ret1   error
}
