name: lighthouse-admin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
    paths:
      - typescript/apps/admin/**
      - .github/workflows/lighthouse-admin.yml

jobs:
  lighthouse:
    name: runner / lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
      - run: yarn install && yarn add @lhci/cli
        working-directory: typescript/apps/admin
      - run: yarn run build
        working-directory: typescript/apps/admin
      - run: yarn run lhci
        working-directory: typescript/apps/admin

    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}