name: sqldef

on:
  pull_request:
    paths:
      - mysql/**/*.sql

jobs:
  mysqldef:
    name:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          sudo apt-get install curl tar
          curl -fSL https://github.com/k0kubun/sqldef/releases/download/v0.11.50/mysqldef_linux_amd64.tar.gz -o mysqldef.tar.gz \
          tar -zxf mysqldef.tar.gz
          chmod +x myqldef
          mv mysqldef /usr/local/bin

      - name: setup
        run: |
          git fetch
          git checkout ${{github.base_ref}}
          git pull
          git checkout ${{github.head_ref}}

          export ARTICLE_DIR=mysql/migrations/article

          git show ${{github.base_ref}}:$ARTICLE_DIR/schema.sql > $ARTICLE_DIR/schema.prev.sql 2>/dev/null
      - name: check diff
        run: |
          mysqldef \
            --file $ARTICLE_DIR/schema.prev.sql \
            --file $ARTICLE_DIR/schema.sql > article

          export ARTICLE_RESULT=$(cat article)

      - name: comment result
        run: |
          envsubst < .github/sqldef_result.md.tpl > comment
          gh pr comment -F ./comment "${URL}"
