name: sqldef

on:
  pull_request:
    paths:
      - mysql/**/*.sql

jobs:
  mysqldef:
    name: mysqldef
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          touch go/.env/server

      - name: prev migrate
        run: |
          git fetch

          git checkout ${{github.base_ref}}
          docker-compose run article-migrate

      - name: current migrate
        run: |
          git checkout ${{github.head_ref}}

          docker-compose run article-migrate > article

          export ARTICLE_RESULT=$(cat article)

      - name: comment result
        run: |
          envsubst < .github/sqldef_result.md.tpl > comment
          gh pr comment -F ./comment "${URL}"

